In [1]:
# Массивы

In [29]:
import numpy as np

In [4]:
data1= [[5.2,3.0,4.5],[9.1,0.1,0.3]]
arrl=np.array(data1)
arrl

array([[5.2, 3. , 4.5],
       [9.1, 0.1, 0.3]])

In [5]:
arrl.ndim

2

In [6]:
arrl.size

6

In [7]:
arrl.shape

(2, 3)

In [8]:
arrl.dtype

dtype('float64')

In [9]:
arrl.itemsize

8

In [21]:
print(np.zeros(10))
print(np.ones(10))
print(np.arange(15))
print(np.linspace(0,1,25))
np.eye(3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[0.         0.04166667 0.08333333 0.125      0.16666667 0.20833333
 0.25       0.29166667 0.33333333 0.375      0.41666667 0.45833333
 0.5        0.54166667 0.58333333 0.625      0.66666667 0.70833333
 0.75       0.79166667 0.83333333 0.875      0.91666667 0.95833333
 1.        ]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
arr=np.array([[1,2,3],[4,5,6]])


In [19]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [20]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [22]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [27]:
np.random.randn(3,4)

array([[-0.49620876,  0.1173593 ,  0.51535986,  0.80942022],
       [ 0.96771334, -1.06747615, -0.71458517,  1.08876138],
       [-1.59854226,  0.38570177, -0.79889045,  0.60707939]])

In [28]:
np.random.randint(0,1000,3)

array([924, 245,  69])

In [32]:
np.arange(15)[8:12] #создали массив из 15 чисел от нуля до четырнадцати и обратились в элеентам с 8 по 12 не включительно

array([ 8,  9, 10, 11])

In [33]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[2]

array([7, 8, 9])

In [34]:
arr2d[1,0]

4

In [35]:
names=np.array(["Bob","Joe","Anne","Bob","Will"])
names=="Bob"

array([ True, False, False,  True, False])

In [36]:
mask=(names=="Bob")|(names=="Will")
mask

array([ True, False, False,  True,  True])

In [37]:
names[mask]

array(['Bob', 'Bob', 'Will'], dtype='<U4')

In [39]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [40]:
arr3d.shape

(2, 2, 3)

In [41]:
arr3d.T #транспонированный массив

array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])

In [43]:
arr3d.T.shape

(3, 2, 2)

In [44]:
np.sqrt(arr3d) #взять квадратный корень из каждого элемента

array([[[1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974]],

       [[2.64575131, 2.82842712, 3.        ],
        [3.16227766, 3.31662479, 3.46410162]]])

In [45]:
np.exp(arr3d) #возвести в экспоненту каждый элемент

array([[[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
        [5.45981500e+01, 1.48413159e+02, 4.03428793e+02]],

       [[1.09663316e+03, 2.98095799e+03, 8.10308393e+03],
        [2.20264658e+04, 5.98741417e+04, 1.62754791e+05]]])

In [46]:
arr=np.random.randn(5,4)
arr

array([[ 1.73676005e+00, -8.99023121e-01,  3.23330997e-02,
        -6.84244696e-01],
       [ 7.12366499e-01, -3.44027777e-01,  6.82263450e-01,
         1.00088282e+00],
       [ 5.87337398e-01,  1.76399187e-02, -1.42646024e-03,
         1.94555283e-01],
       [-1.06195146e+00,  1.16451319e+00, -1.20026541e-01,
         3.02781402e-01],
       [ 2.22777826e-01, -1.99772031e+00,  1.54478947e+00,
         6.52249571e-01]])

In [47]:
arr.shape

(5, 4)

In [48]:
arr.mean()

0.18714148036626427

In [49]:
arr.sum()

3.7428296073252856

In [51]:
arr.max()==np.max(arr)

True

In [52]:
arr.sum(axis=0)

array([ 2.19729032, -2.0586181 ,  2.13793302,  1.46622438])

In [53]:
arr=np.array([[0,1,2],[3,4,5],[6,7,8]])

In [54]:
arr.cumsum(axis=0) #суммируем по строкам

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [55]:
arr.cumprod(axis=0)

array([[ 0,  1,  2],
       [ 0,  4, 10],
       [ 0, 28, 80]], dtype=int32)

In [64]:
arr=np.arange(10)

In [57]:
np.save("some_array", arr)
np.load("some_array.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
np.savez("array_archive.npz", a=arr, b=arr[:5])

In [69]:
arch=np.load("array_archive.npz")
arch["b"]

array([0, 1, 2, 3, 4])